[project]
name = "docu-mind"
version = "0.1.0"
description = ""
authors = [
    {name = "Ashminita",email = "ashminitab@mindfiresolutions.com"}
]
readme = "README.md"

requires-python = ">=3.12,<3.13"
dependencies = [
    "langchain (>=1.4.0,<2.0.0)",
    "langgraph (>=1.2.11,<2.0.0)",
    "langsmith (>=0.12.2,<0.13.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "chromadb (>=1.5.9,<2.0.0)",
    "llama-index (>=0.14.24,<0.15.0)",
    "llama-index-vector-stores-chroma (>=0.6.0,<0.7.0)",
    "llama-index-embeddings-gemini (>=0.4.2,<0.5.0)",
    "llama-index-llms-gemini (>=0.6.2,<0.7.0)",
    "langchain-google-genai (>=4.4.0,<5.0.0)",
    "llama-index-embeddings-google-genai (>=0.6.0,<0.7.0)",
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.52.4,<0.53.0)",
    "pydantic (>=2.13.5,<3.0.0)",
    "streamlit (>=1.63.0,<2.0.0)",
    "requests (>=2.34.2,<3.0.0)",
    "ragas (>=0.4.3,<0.5.0)",
    "datasets (>=5.0.1,<6.0.0)",
    "langchain-google-vertexai (>=3.2.4,<4.0.0)"
]

[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
